site_name: study_blog
site_description: This is a project for learning Django
repo_url: https://github.com/seolacarrano/study_blog
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/seolacarrano">seolacarrano</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
